//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadSet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadsetDetail
    {
        public int Id { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string Colour { get; set; }
        public string Bluetooth { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
